# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "asterisk-manager"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Wulff"]
  s.date = "2013-04-28"
  s.description = "Ruby Gem for connecting to an Asterisk server via the AMI (Asterisk Manager Interface) protocol."
  s.email = "johnw@orcasnet.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/asterisk-manager.rb",
    "lib/asterisk-manager/call.rb",
    "lib/asterisk-manager/call_event_observer.rb",
    "lib/asterisk-manager/channel.rb",
    "lib/asterisk-manager/channel_event_observer.rb",
    "lib/asterisk-manager/channel_event_poller.rb",
    "lib/asterisk-manager/conference.rb",
    "lib/asterisk-manager/connection.rb",
    "lib/asterisk-manager/event.rb",
    "lib/asterisk-manager/event_listener.rb",
    "script/curses_display",
    "script/event_stream",
    "spec/asterisk-manager_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/jwulff/asterisk-manager"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Ruby Gem for connecting to an Asterisk server via the AMI (Asterisk Manager Interface) protocol."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

